<?php
echo '<div id="content">';
echo '	<div class="content">';
echo '		<ul class="article">';
echo '			<li>';
echo '				<fieldset>';
echo '					<legend>Langage de programmation web.</legend>';
echo ' 					<img src="includes/images/PHP.png" width="150px">Le <u>PHP</u>, Hypertext Preprocessor, plus connu sous son sigle PHP, est un langage de scripts libre principalement utilisé pour produire des pages Web dynamiques via un serveur'; 
echo '					HTTP, mais pouvant également fonctionner comme n\'importe quel langage interprété de façon locale, en exécutant les programmes en ligne de commande. PHP est un langage impératif';
echo ' 					disposant depuis la version 5 de fonctionnalités de modèle objet complet. En raison de la richesse de sa bibliothèque, on désigne parfois PHP comme une plate-forme plus qu\'un';
echo ' 					simple langage.';
echo '					<br>';
echo ' 					<br>';
echo '					<img src="includes/images/Js.png" width="150px"><u>JavaScript</u> est un langage de programmation de scripts principalement utilisé dans les pages web interactives, mais aussi côté serveur. C\'est un langage ';
echo '					orienté objet à prototype, c\'est-à-dire que les bases du langage et ses principales interfaces sont fournies par des objets qui ne sont pas des instances ';
echo '					de classes, mais qui sont ';
echo '					chacun équipés de constructeurs permettant de créer leurs propriétés, et notamment une propriété de prototypage qui permet d\'en créer des objets ';
echo '					héritiers personnalisés.';
echo '					Le langage a été créé en 1995 par Brendan Eich (Brendan Eich étant membre du conseil d\'administration de la fondation Mozilla) pour le compte de Netscape';
echo '					Communications Corporation. Le';
echo '					langage, actuellement à la version 1.8.2 est une implémentation de la 3e version de la norme ECMA-262 qui intègre également des éléments inspirés du ';
echo '					langage Python. La version 1.8.5 du';
echo '					langage est prévue pour intégrer la 5e version du standard ECMA.';
echo '					<br>';
echo '					<br>';
echo '					<img src="includes/images/HTML.png" width="150px">L’<u>Hypertext Markup Language</u>, généralement abrégé HTML, est le format de données conçu pour représenter les pages web. C’est un langage de balisage qui ';
echo '					permet d’écrire de l’hypertexte, d’où son nom. HTML permet également de structurer sémantiquement et de mettre en forme le contenu des pages, d’inclure des ';
echo '					ressources multimédias dont ';
echo '					des images, des formulaires de saisie, et des éléments programmables tels que des applets. Il permet de créer des documents interopérables avec des ';
echo '					équipements très variés de manière conforme aux exigences de l’accessibilité du web. Il est souvent utilisé conjointement avec des langages de ';
echo '					programmation (JavaScript) et des formats de présentation (feuilles de style ';
echo '					en cascade). HTML est initialement dérivé du Standard Generalized Markup Language (SGML).';
echo '				</fieldset>';
echo '            </li>';
echo '			<li>';
echo '				<div class="precedent">';
echo '					<a href="index.php?page=the&the=info" >&laquo; retour</a>';
echo '				</div>';
echo '			</li>';
echo '        </ul>';
echo '    </div>';
echo '</div>';
?>