<?php
echo '<div id="content">';
echo '	<div class="content">';
echo '		<ul class="article">';
echo '			<li>';
echo '				<fieldset>';
echo '					<legend>Modem et routeur.</legend>';
echo ' 					<img src="includes/images/theorie/routeur.png" width="200px">Un <b>routeur</b> est un équipement d\'interconnexion de réseaux informatiques permettant d\'assurer le routage des paquets entre deux réseaux ou plus afin de déterminer ';
echo '					le chemin qu\'un paquet de données va emprunter. ';
echo '					<br>';
echo '					Lorsqu\'un utilisateur appelle une URL, le client Web (navigateur) interroge le serveur de noms, qui lui indique en retour l\'adresse IP de la machine visée. ';
echo '					<br>';
echo '					Son poste de travail envoie la requête au routeur le plus proche, c\'est-à-dire à la passerelle par défaut du réseau sur lequel il se trouve. Ce routeur va ainsi ';
echo '					déterminer la prochaine machine à laquelle les données vont être acheminées de manière à ce que le chemin choisi soit le meilleur. ';
echo '					<br>';
echo '					Pour y parvenir, les routeurs tiennent à jour des tables de routage, véritable cartographie des itinéraires à suivre en fonction de l\'adresse visée. Il existe de ';
echo '					nombreux protocoles dédiés à cette tâche. ';
echo '					<br>';
echo '					En plus de leur fonction de routage, les routeurs permettent de manipuler les données circulant sous forme de datagrammes afin d\'assurer le passage d\'un type de ';
echo '					réseau à un autre. Or, dans la mesure où les réseaux n\'ont pas les mêmes capacités en terme de taille de paquets de données, les routeurs sont chargés de ';
echo '					fragmenter les paquets de données pour permettre leur libre circulation. ';
echo '					<br>';
echo ' 					<br>';
echo '					<img src="includes/images/theorie/modem.png" width="200px">Le <b>modem</b> est le périphérique utilisé pour transférer des informations entre plusieurs ordinateurs'; 
echo '					via un support de transmission filaire (lignes téléphoniques par exemple). Les ordinateurs fonctionnent de façon numérique, ils utilisent le codage binaire (une'; 
echo '					série de 0 et de 1), mais les lignes téléphoniques sont analogiques. Les signaux numériques passent d\'une valeur à une autre, il n\'y a pas de milieu, de moitié,'; 
echo '					c\'est du « Tout Ou Rien » (un ou zéro). Les signaux analogiques par contre n\'évoluent pas « par pas », ils évoluent de façon continue. ';
echo '					<br>';
echo '					Ainsi, le modem module les informations numériques en ondes analogiques. En sens inverse, il démodule les données analogiques pour les convertir en numérique.'; 
echo '					Le mot « modem » est ainsi un acronyme pour « <b>MO</b>dulateur/<b>DEM</b>odulateur ».'; 
echo '					<br>';
echo '					La vitesse de transmission du modem est généralement exprimée en bauds, en hommage à Emile Baudot (11 septembre 1845 - 28 mars 1903), un célèbre ingénieur'; 
echo '					français ayant oeuvré dans les télécommunications. Cette unité de vitesse de transmission d\'informations caractérise la fréquence de (dé)modulation, c\'est-à-dire'; 
echo '					le nombre de changements d\'état que le modem fait subir au signal par seconde. Ainsi, le débit en bauds n\'est pas tout à fait égal au débit en bits par'; 
echo '					secondes, car plus d\'un changement d\'état du signal peut être nécessaire pour coder un bit. ';
echo '				</fieldset>';
echo '            </li>';
echo '			<li>';
echo '				<div class="precedent">';
echo '					<a href="index.php?page=the&the=info" >&laquo; retour</a>';
echo '				</div>';
echo '			</li>';
echo '        </ul>';
echo '    </div>';
echo '</div>';
?>